component_depth: 3

languages:
  - name: cpp
    production:
      include:
        - .*/src/.*\.c
        - .*/src/drvr\.c
      exclude:
        - .*/src/ast/parser\.c
        - .*/src/ast/lexer\.c
        - .*/src/lib/soundpipe\.c
    test:
      include:
        - .*/tests/plugins/.*\.c

  - name: java
    test:
      include:
        - .*/examples/.*\.gw
        - .*/tests/.*/.*\.gw

  - name: script
    test:
      include:
      - .*/utils/.*\.sh
      - .*/test/sh/.*\.sh
