component_depth: 3

languages:
  - name: cpp
    production:
      include:
        - /src/.*\.c
      exclude:
        - /src/drvr/.*\.c
        - /src/vm/vm.c
        - /include/.*\.h
        - /tests/import/.*\.c
    test:
      include:
        - /tests/import/.*\.c

  - name: go
    production:
      include:
       - fake_entry
    test:
      include:
        - /docs/.*/.*\.mdr
        - /examples/.*/.*\.gw
        - /tests/.*/.*\.gw
        - /tests/benchmark/.*\..*

  - name: script
    production:
      include:
       - fake_entry
    test:
      include:
      - /help/.*\.sh
      - /tests/sh/.*\.sh
