component_depth: 2

languages:
  - name: cpp
    production:
      include:
        - .*/src/.*\.c
        - .*/src/drvr/.c
    test:
      include:
        - .*/examples/.*\.gw
        - .*/test/.*/.*\.gw

  - name: script
    production:
      include:
        - .*/utils/.*\.sh
    test:
      include:
      - .*/test/sh/.*\.sh
