component_depth: 3

languages:
  - name: cpp
    production:
      include:
        - /src/.*\.c
      exclude:
        - /src/ast/parser\.c
        - /src/ast/lexer\.c
        - /src/lib/soundpipe\.c
    test:
      include:
        - /tests/test_plugins/.*\.c

  - name: go
    production:
      include:
       - fake_entry
    test:
      include:
        - /examples/.*\.gw
        - /examples/complex/.*\.gw
        - /tests/bug/.*\.gw
        - /tests/error/.*\.gw
        - /tests/test_plugin/.*\.gw
        - /tests/tree/.*\.gw
        - /tests/ugen_coverage/.*\.gw

  - name: script
    production:
      include:
       - fake_entry
    test:
      include:
      - /utils/.*\.sh
      - /tests/sh/.*\.sh
