dist: trusty
language: c
sudo: false

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - lua5.2
    - valgrind
    - libsndfile1
    - libsndfile1-dev

env:
  global:
    - D_FUNC=dummy_driver
    - ALSA_D=0
    - SOUNDPIPE_DATA_DIR=$TRAVIS_BUILD_DIR/Soundpipe/modules/data
    - BISON_VERSION=bison-3.0.4
    - GWION_DOC_DIR=./doc
    - GWION_API_DIR=./api
    - GWION_TOK_DIR=./tok
    - GWION_TAG_DIR=./tag
    - GWION_PLUG_DIR=./plug
    - MY_PATH=$PATH
  matrix:
    - GW_FLOAT_TYPE=float  SP_BRANCH=dev
    - GW_FLOAT_TYPE=double SP_BRANCH=dev
    - GW_FLOAT_TYPE=float  SP_BRANCH=master SPA_D=0
    - GW_FLOAT_TYPE=double SP_BRANCH=master SPA_D=0

matrix:
  fast_finish: true
  allow_failures:
  - os: osx

compiler:
- clang
- gcc

before_install:
  - pip install --user cpp-coveralls

before_script:
  - export PATH=$PATH:$PWD/bats/bin:$PWD/bison-3.0.4/src:$PWD/bin:$PATH
  - export CFLAGS+=-ISoundpipe/h
  - if [ $CC = 'gcc' ]; then if [ $GW_FLOAT_TYPE = 'float' ]; then if [ $SP_BRANCH = 'dev' ]; then CFALGS+=--coverage; fi; fi; fi
  - export LIBARY_PATH=Soundpipe
  - export YACC=$PWD/bison-3.0.4/src/bison
  - echo $TRAVIS_BUILD_DIR
  - bash util/travis_prepare.sh

script:
  - make && sh util/test.sh

branches:
  - only:
    - dev

after_success:
  - if [ $CC = 'gcc' ]; then if [ $GW_FLOAT_TYPE = 'float' ]; then if [ $SP_BRANCH = 'dev' ]; then coveralls --exclude lib --exclude tests --gcov-options '\-lp'; fi; fi; fi
