language: c
sudo: false

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - valgrind
    - libsndfile1-dev
    - lcov

cache:
  directories:
    - Soundpipe

env:
  global:
    - ALSA_D=0
    - SOUNDPIPE_LIB=$TRAVIS_BUILD_DIR/Soundpipe/libsoundpipe.a
    - SOUNDPIPE_INC=-I$TRAVIS_BUILD_DIR/Soundpipe/h
    - DATA=$TRAVIS_BUILD_DIR/Soundpipe/modules/data
    - GWION_ADD_DIR=$TRAVIS_BUILD_DIR/add
    - USE_MEMCHECK=1
    - PREFIX=$TRAVIS_BUILD_DIR
  matrix:
    - USE_DOUBLE=1 SP_BRANCH=dev
    - USE_DOUBLE=0 SP_BRANCH=dev

matrix:
  fast_finish: true
  allow_failures:
  - os: osx

compiler:
  - gcc
  - clang

install:
  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.1  ]; then gem install coveralls-lcov; fi


before_script:
  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.1  ]; then export USE_COVERAGE=1; fi
  - bash utils/travis_prepare.sh

script:
  - ./configure && make clean all test
after_success:
  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.1  ]; then bash utils/lcov_helper.sh; fi

after_failure:
  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.5  ]; then valgrind ./gwion; fi

git:
  submodules: false
