dist: trusty
language: c
sudo: false

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - lua5.2
    - valgrind
    - libsndfile1
    - libsndfile1-dev

env:
  global:
    - SOUNDPIPE_DATA_DIR=Soundpipe/modules/data
    - BISON_VERSION=bison-3.0.4
    - GWION_DOC_DIR="./doc"
    - GWION_API_DIR="./api"
    - GWION_TOK_DIR="./tok"
    - GWION_TAG_DIR="./tag"
    - GWION_PLUG_DIR="./plug"
  matrix:
    - GW_FLOAT_TYPE="float"
    - GW_FLOAT_TYPE="double"

matrix:
  fast_finish: true
  allow_failures:
  - os: osx

compiler:
- clang
- gcc

before_script:
- export PATH=$PATH:$PWD/bats/bin:$PWD/bison-3.0.4/src:$PWD/bin:$PATH
- export CFLAGS+=-ISoundpipe/h
- export LIBARY_PATH=Soundpipe
- export YACC=$PWD/bison-3.0.4/src/bison
- bash util/travis_prepare.sh

script:
  - make && sh util/test.sh

branches:
  - only:
    - dev
