dist: trusty
language: c
sudo: false

os:
  - linux
  - osx

addons:
  apt:
    packages:
#    - lua5.2
    - valgrind
    - libsndfile1
    - libsndfile1-dev

env:
  global:
    - GWION_HAS_DIR=1
    - DEBUG=1
    - D_FUNC=dummy_driver
    - ALSA_D=0
    - SOUNDPIPE_D=0
    - SPA_D=0
#    - SNDFILE_D=0
    - SOUNDPIPE_DATA_DIR=$TRAVIS_BUILD_DIR/Soundpipe/modules/data
    - SOUNDPIPE_LIB=$TRAVIS_BUILD_DIR/Soundpipe/libsoundpipe.a
    - SOUNDPIPE_INC=-I$TRAVIS_BUILD_DIR/Soundpipe/h
    - DATA=$TRAVIS_BUILD_DIR/Soundpipe/modules/data
    - BISON_VERSION=bison-3.0.4
    - GWION_DOC_DIR=doc
    - GWION_API_DIR=api
    - GWION_TOK_DIR=tok
    - GWION_TAG_DIR=tag
    - GWION_PLUG_DIR=plug
  matrix:
    - USE_DOUBLE=1 SP_BRANCH=dev
#    - GW_FLOAT_TYPE=float  SP_BRANCH=dev COVERAGE=1
#    - GW_FLOAT_TYPE=double USE_DOUBLE=1 SP_BRANCH=dev
#    - GW_FLOAT_TYPE=float  SP_BRANCH=master SPA_D=0
#    - GW_FLOAT_TYPE=double USE_DOUBLE=1 SP_BRANCH=master SPA_D=0

matrix:
  fast_finish: true
  allow_failures:
  - os: osx

compiler:
  - gcc
  - clang

before_install:
#  - pip install hererocks
#  - hererocks lua_install -r^ --"lua=5.2"
#  - export PATH=$PATH:$PWD/lua_install/bin
  - echo $TRAVIS_JOB_NUMBER
  - [ $(echo $TRAVIS_JOB_NUMBER | tr '.' -f2) -eq 1 ] && export USE_COVERAGE=1
#  - [ $TRAVIS_JOB_NUMBER -eq 1 ] && pip install --user cpp-coveralls; fi; fi; fi

#install: #next test system?
#  - luarocks install busted

before_script:
  - export PATH=$PATH:$PWD/bats/bin:$PWD/bison-3.0.4/src:$PWD/bin:$PATH
  - export CFLAGS+=-I$TRAVIS_BUILD_DIR/Soundpipe/h
  - export YACC=$PWD/bison-3.0.4/src/bison
  - bash util/travis_prepare.sh

branches:
  - only:
    - dev

after_success:
#  - [ $TRAVIS_JOB_NUMBER -eq 1 ] && for a in tests/bug/*; do ./gwion $a; done
#  - [ $TRAVIS_JOB_NUMBER -eq 1 ] && ./gwion examples/doc.gw
#  - [ $TRAVIS_JOB_NUMBER -eq 1 ] && bash util/coverage.sh run
#  - [ $TRAVIS_JOB_NUMBER -eq 1 ] && coveralls --exclude Gwion-plug --exclude $BISON_VERSION --exclude Soundpipe --exclude bison --exclude bats --exclude examples --exclude drvr --exclude coverage --exclude lua_install --exclude eval/lexer.c --exclude eval/parser.c --gcov-options '\-lp'
