language: bash
before_install:
  - sudo apt-get install libsndfile1 libsndfile1-dev
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
  - sudo apt-get install valgrind
script:
  - DIR=$PWD
  - git clone https://github.com/PaulBatchelor/Soundpipe.git
  - cd Soundpipe; sudo make install
  - cd $DIR
  - sed -i "s/CFLAGS+=-DD_FUNC=alsa_driver/CFLAGS+=-DD_FUNC=dummy-driver/" config.def.mk
  - sed -i "s/ALSA_D/#ALSA_D/" config.def.mk
  - make
  - sh util/test.sh
