language: c
#sudo: required
os:
  - linux
#  - osx
  - windows

addons:
#  coverity_scan:
#    project:
#      name: "fennecdjay/Gwion"
#      description: "<Your project description here>"
#    notification_email: astor.jeremie@wanadoo.fr
#    build_command: make
#    branch_pattern: coverity_scan
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-7
    packages:
    - valgrind
    - lcov
    - gcc-8
    - clang-7
env:
  global:
  - CC_TEST_REPORTER_ID=1ef7168aff2b8902922b345c8b1b9be3fd2442fa4f2096634b42235bcbaa2c47
  - CIFLAGS=-Wno-attributes
  - GWION_ADD_DIR=$TRAVIS_BUILD_DIR/add
  - GWION_TEST_DIR=tmp_test
  - PREFIX=$TRAVIS_BUILD_DIR
#  - secure: qC1iGXWyzrJrn6pIxZup0CYThjZC44NuEStU50wx3Jdi1owYkkQ/eXWw55TvhswmnnO7l+wQsN2RnP6zsjJTq6wuNjAyG8w89rgCevbCpOu5vZAWF0+/c5H7qDG+NS9aumfd53QPC55ZcjjjM+5j71+J8XXoj+n4ygR5dVtTk/xF4sTBBwyaUkG9r/Hoocd3gtd3Up/ZlDYQd5/tCrfiFcWvAs4197LPfCDIW7k/tnXEmKV3le/yTXU0/ZByzjGQkhhpqvMqh3BTQrKExxeBt8utqnwLVwUAIWnACUIJz8bjyWWX++DwP1cFExAUBWB21A4i/qpXAieu7whcwE/hPkrVJjqEedbXNonyFHAwwOVhPIckk2OVzD6tCNp8IJZkccq8ONbqM/WpPAKip//13wttDvsDRgva2nkS7LZ6n/V1MHye6OgZD3778bty6YGOSkyEiT9ryZGaDrGbNbdXcAyCUmbd8a/N1RnQC+TSkvRBAhVL50dgSHNYNXZNn02hqiD/QNDqgdjOQ/jkgROQxMj8EnsVDPTOWIYkKpiTawQF9WqCPdQLl7+P5+uuUhfeMiyohu90yDOl7BXxhS8FJt/YUCMBLGS3OsmnVpA5XoG2aBZKDz1gXedNcQJ1JAEB0XO5mSJn4jXbDtI9QMZu/jNxm1TmyJaItv1l0ln3zn0=
  - USE_MEMCHECK=1
  matrix:
  - USE_DOUBLE=1
  - USE_DOUBLE=0

matrix:
  allow_failures:
   - os: windows
#     - osx

compiler:
  - gcc
#  - clang

install:
  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.1  ]; then gem install coveralls-lcov; fi;
  - if [ $(uname) != "Linux" ] && [ $(uname) != "Darwin" ]; then 
      choco install make;
      export BUILD_ON_WINDOWS=1;
      git clone https://github.com/dlfcn-win32/dlfcn-win32 && cd dlfcn-win32 && ./configure && make.exe && cd ..;
      export VALGRIND="NO_VALGRIND";
      export SEVERITY=1;
      export CFLAGS="$CFLAGS -Idlfcn-win32";
      export LDFLAGS="$LDLAGS -Ldlfcn-win32 -lpsapi -shared -fPIC dlfcn-win32/libdl.a";
      export LIBS="$LIBS -lpsapi -shared -fPIC";
    fi;

before_script:
  - git submodule update --init util ast;
  - if [ $(uname) = "Linux" ]; then
      if [ $CC = gcc ]; then export CC=gcc-8;
      elif [ $CC = clang ]; then export CC=clang-7;
     fi;
    elif [ $(uname) = "Darwin" ]; then brew update;
    fi;

#  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.1  ]; then
#      export USE_COVERAGE=1;
#      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
#      chmod +x ./cc-test-reporter;
#    ./cc-test-reporter before-build;
#    fi;
  - mkdir -p "$GWION_ADD_DIR" "$GWION_TEST_DIR"

script:
  - if [ $(uname) = "Linux" ] || [ $(uname) = "Darwin" ];
    then make && make test;
    else make.exe && make.exe test && ls;
    fi;

after_success:
  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.1  ]; then
      bash help/lcov.sh;
      ./cc-test-reporter after-build -r $TRAVIS_TEST_RESULT;
    fi;

git:
  submodules: false
