language: c
sudo: false

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - valgrind
    - lcov

env:
  global:
    - CFLAGS=-Wno-attributes
    - GWION_ADD_DIR=$TRAVIS_BUILD_DIR/add
    - PREFIX=$TRAVIS_BUILD_DIR
  matrix:
    - USE_DOUBLE=1
    - USE_DOUBLE=0

matrix:
  fast_finish: true
  allow_failures:
  - os: osx

compiler:
  - gcc
  - clang

install:
  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.1  ]; then gem install coveralls-lcov; fi

before_script:
  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.1  ]; then export USE_COVERAGE=1; fi
  - bash utils/travis_prepare.sh

script:
  - make && make test

after_success:
  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.1  ]; then bash utils/lcov_helper.sh; fi

after_failure:
  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.5  ]; then valgrind ./gwion; fi

git:
  submodules: false
