language: c

os:
  - linux
  - osx


compiler:
  - clang
  - gcc

before_install:
#bats
  - git clone https://github.com/sstephenson/bats.git
  - pushd bats && sudo ./install.sh /usr/local && popd
  - wget http://ftp.gnu.org/gnu/bison/bison-3.0.4.tar.gz
  - tar -xzf bison-3.0.4.tar.gz
  - pushd bison-3.0.4 && ./configure && make && sudo make install && popd
  - git clone https://github.com/paulbatchelor/Soundpipe.git
  - if [ $TRAVIS_OS_NAME = "osx" ]; then sh util/osx_prepare.sh; else sh util/linux_prepare.sh; fi

env:
   matrix:
    - GW_FLOAT_TYPE=float
    - GW_FLOAT_TYPE=double

script:
  - make
  - sh util/test.sh
