language: bash
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
  - sudo apt-get install valgrind
script:
  - DIR=$PWD
  - git clone https://github.com/PaulBatchelor/Soundpipe.git
  - cd Soundpipe; sudo make install
  - cd $DIR
  - make
  - sh util/test.sh
