language: c

env:
  global:
   - secure: "DnhraXW8wdrP5UzvQbAtarIUFk0i78py+in2VHphS7PG4Tp2qmAyAcf3NNZTm75E/vDQbeGQpEPHORxYxHr3KLfhpqeumQ+o/TzGD42zNHOedSKmr4khVkYohAaI7yC/+j/W5ndvnohMdrNAkdxVMg6g1HmY8nqnn41qHzebqzpFytxbBQpNe4pCxHZb4ujArxFIZcaYSudQS5CpdEzVafZvtcqLyZzrgpH+ys8AYxbspdHT5VvY/cG4fZZyfz9v3I/YadP+/Yes+CbAeZHdv3+2vBiXllHspcfkSA5yS93Mmzm0zT1obl3F1TCIQG7BDML96haZfW7sqcYXMnJfK5TamUGB1pVDf8kV10rm+Fc8jlnmmdQENktaPZs+5Y4SEcFdc9mgjDPjvxQ1vXr5LkJs/daNzhhK8psSy/PcVKKrpuHEc9I3VVE8MN81f+HYIdkM428H7H8nUqAxutvvrIES3ZA2U/+Yyzb4i+G1FQGzynM3YJkjoSWoXMjoMY9Mu1Posvbs6bAgS7nHOX2IHS+WUezjEb4A9eL7nfIn1WMMFKTv73yIVsykjPCNnQBasZakleRgsUrcqvRDR3ak42xjOlTw+PN07F/3szuA8Uk06us/6F2kABu+FZmX+hkHmONmFRF5biB2T4nyWZqoQgB/DB+G/kQ4On+WmvMkSkk="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

before_install:
  - sudo apt-get install libsndfile1 libsndfile1-dev lua5.2

before_script:
# need recent bison
  - wget http://ftp.gnu.org/gnu/bison/bison-3.0.4.tar.gz
  - tar -xzf bison-3.0.4.tar.gz
  - pushd bison-3.0.4 && ./configure \-\-prefix=$PWD/../bison && make install && popd && export PATH=bison-3.0.4/src:$PATH
#soundpipe (dev) part
  - git clone -b dev https://github.com/paulbatchelor/Soundpipe.git
  - pushd Soundpipe && sed -i 's/#USE_DOUBLE/USE_DOUBLE/' config.def.mk && make && popd
  - export CFLAGS+=-ISoundpipe/h
  - export LIBARY_PATH=Soundpipe
  - sed -i "s/ALSA_D/#ALSA_D/" config.def.mk
  - sed -i "s/CFLAGS+=-DD_FUNC=alsa_driver/CFLAGS+=-DD_FUNC=dummy_driver/" config.def.mk
  - sed -i 's/${YACC}/..\/bison-3.0.4\/src\/bison/' ast/Makefile
  - export PATH=$PWD/bin:$PATH
  - export BISON=$PWD/bison-3.0.4/src/bison
  - sed -i "s/-lsoundpipe/Soundpipe\/libsoundpipe.a/" Makefile

script:
  - make
addons:
  coverity_scan:
    project:
      name: "fennecdjay/Gwion"
      description: "Build submitted via Travis CI"
    notification_email: astor.jeremie@wanadoo.fr
    build_command_prepend: "make && make clean"
    build_command:   "make"
