dist: trusty
language: c
sudo: false

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - valgrind
    - libsndfile1
    - libsndfile1-dev
    - lcov

cache:
  directories:
    - Soundpipe

env:
  global:
    - ALSA_D=0
    - SOUNDPIPE_LIB=$TRAVIS_BUILD_DIR/Soundpipe/libsoundpipe.a
    - SOUNDPIPE_INC=-I$TRAVIS_BUILD_DIR/Soundpipe/h
    - DATA=$TRAVIS_BUILD_DIR/Soundpipe/modules/data
    - GWION_DOC_DIR=$TRAVIS_BUILD_DIR/doc
    - GWION_API_DIR=$TRAVIS_BUILD_DIR/api
    - GWION_TOK_DIR=$TRAVIS_BUILD_DIR/tok
    - GWION_TAG_DIR=$TRAVIS_BUILD_DIR/tag
    - GWION_ADD_DIR=$TRAVIS_BUILD_DIR/add
    - USE_MEMCHECK=1
    - PREFIX=$TRAVIS_BUILD_DIR
  matrix:
    - USE_DOUBLE=1 SP_BRANCH=dev
    - USE_DOUBLE=0 SP_BRANCH=dev

matrix:
  include: 
    os: osx
    compliler:
      - clang
      - gcc
    env: USE_DOUBLE=0 SP_BRANCH=dev
  fast_finish: true
  allow_failures:
  - os: osx

compiler:
  - gcc
  - clang

install:
  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.1 ]; then gem install coveralls-lcov; fi


before_script:
  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.1 ]; then export USE_COVERAGE=1; fi
#  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.1 ]; then pip install --user cpp-coveralls; fi
  - bash util/travis_prepare.sh

after_success:
#  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.1 ]; then bash util/coverage.sh after_success; fi
  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.1 ]; then bash util/lcov_helper.sh; fi
  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.1 ]; then coveralls-lcov gwion.info; fi
  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.9 ]; then for a in test/bug/*; do echo $a; ./gwion $a; done; fi
  - if [ $TRAVIS_JOB_NUMBER = ${TRAVIS_BUILD_NUMBER}.10 ]; then for a in test/bug/*; do echo $a; ./gwion $a; done; fi

git:
  submodules: false

