language: bash
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
  - sudo apt-get install valgrind
  - sudo sudo apt-get install gcc-6
  - sudo update-alternatives --config gcc
  - sudo apt-get install libsndfile1 libsndfile1-dev
script:
  - DIR=$PWD
  - wget http://ftp.gnu.org/gnu/bison/bison-3.0.4.tar.gz
  - tar -xzf bison-3.0.4.tar.gz
  - cd bison-3.0.4
  - ./configure
  - make
  - sudo make install
  - cd $DIR
  - git clone --branch=dev https://github.com/PaulBatchelor/Soundpipe.git
  - cd Soundpipe; sudo make install
  - cd $DIR
  - sed -i "s/CFLAGS+=-DD_FUNC=alsa_driver/CFLAGS+=-DD_FUNC=dummy_driver/" config.def.mk
  - sed -i "s/ALSA_D/#ALSA_D/" config.def.mk
  - make
  - sh util/test.sh
