[book]
authors = ["Jérémie Astor", "Pranav Joglekar", "Amber Zeller"]
title = "Gwion"
description = "Tutorial and reference for gwion"
language = "en"

[output.html]
default-theme = "rust"
additional-css = ["custom.css", "ansi2html.css"]
git-repository-url ="https://github.com/fennecdjay/Gwion"

[output.html.fold]
enable = true
level = 0
