[book]
authors = ["Jérémie Astor"]
title = "Gwion"
google-analytics = UA-173541140-1

[output.html]
default-theme = "rust"
additional-css = ["custom.css", "ansi2html.css"]
git-repository-url ="https://github.com/fennecdjay/Gwion"
[output.html.fold]
enable = true
level = 0
