[book]
authors = ["Jérémie Astor"]
title = "Gwion"

[output.html]
default-theme = "rust"
additional-css = ["custom.css"]
git-repository-url ="https://github.com/fennecdjay/Gwion"

[output.html.fold]
enable = true
level = 0
