name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1

    - uses: actions/cache@v1
      id: mdr-bin
      with:
        path: mdr
        key: ${{ runner.os }}-mdr

    - name: Mdr
      if: steps.mdr-bin.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/fennecdjay/mdr
        cd mdr
        cabal update
        cabal install --only-dependencies
        cabal configure --enable-tests
        cabal build
        cabal install

    - name: Mdr
      if: steps.mdr-bin.outputs.cache-hit == 'true'
      run: |
        if [ $(git rev-parse HEAD) = $(git ls-remote https://github.com/fennecdjay/mdr.git HEAD | cut -f1) ]
        then exit 0
        fi
        cd mdr
        git pull
        cabal update
        cabal install --only-dependencies
        cabal configure --enable-tests
        cabal build
        cabal install

    - name: Gwion
      run: |
        git clone https://github.com/fennecdjay/Gwion
        cd Gwion
        git submodule update --init util ast
        make
        sudo make install

    - name: Benchmark
      run: |
        echo 1 | sudo tee /proc/sys/kernel/perf_event_paranoid
        git clone https://github.com/wren-lang/wren
        cd wren
        make
        cd ..
        sudo apt-get install gnuplot lua5.3
        ln -s $(which lua5.3) lua
        export PATH=./wren:$PATH
        export PATH=.:$PATH
        bash scripts/benchmark.sh

    - name: MdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'

    - name: try mdr
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        export PATH=~/.cabal/bin:$PATH
        make build
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f book
        git commit -m "add book"
        git remote set-url origin https://${{ secrets.GWION_TOKEN }}@github.com/fennecdjay/Gwion.git
        git push origin :gh-pages || true
        git subtree push --prefix book origin gh-pages
