name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
    - name: Mdr
      run: |
        git clone https://github.com/fennecdjay/mdr
        cd mdr
        cabal update
        cabal install --only-dependencies
        cabal configure --enable-tests
        cabal build
        cabal install
    - name: Gwion
      run: |
        git clone https://github.com/fennecdjay/Gwion
        cd Gwion
        git submodule update --init util ast
        make

    - name: MdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'

    - name: try mdr
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        export PATH=~/.cabal/bin:$PATH
        export PATH=./Gwion:$PATH
        make build
        git branch -r | grep gh-pages && git push origin :gh-pages || true
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f book
        git commit -m "add book"
        git push https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${REPOSITORY}.git HEAD:gh_pages
