name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    
    steps:
    - uses: actions/checkout@v1
      name: Checkout
    - uses: actions/setup-python@v1
      name: Setup Python
    - uses: actions/setup-ruby@v1
      name: Setup Ruby

    - uses: actions/cache@v1
      name: Mdr [ cache ]
      id: mdr-bin
      with:
        path: mdr
        key: ${{ runner.os }}-mdr

    - uses: actions/cache@v1
      name: Results [ cache ]
      id: results
      with:
        path: benchmark/results
        key: ${{ runner.os }}-results

    - name: Mdr
      if: steps.mdr-bin.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/fennecdjay/mdr
        cd mdr
        make

    - name: Mdr
      if: steps.mdr-bin.outputs.cache-hit == 'true'
      run: |
        cd mdr
        git pull
        git checkout master
        make

    - uses: actions/cache@v1
      name: Gwion [ cache ]
      id: gwion-bin
      with:
        path: Gwion
        key: ${{ runner.os }}-gwion

    - name: Gwion
      if: steps.gwion-bin.outputs.cache-hit != 'true'
      uses: fennecdjay/gwion-action@v1

    - name: Gwion [ update ]
      if: steps.gwion-bin.outputs.cache-hit == 'true'
      run: |
        cd Gwion
        if [ $(git rev-parse HEAD) != $(git ls-remote https://github.com/fennecdjay/Gwion.git HEAD | cut -f1) ]
        then
          git pull
          git submodule update util ast
          make
        fi
        cp gwion ..

    - uses: fennecdjay/emojify-docker-action@v2
      name: Emojify
      with:
         directory: 'docs'

    - name: MdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'

    - name: Get becnhmarks
      run: |
        git submodule update --init gwion-benchmark
        cd benchmark
        git checkout results
        git pull

    - name: Build book
      run: |
        export PATH=mdr:$PATH
        export PATH=Gwion:$PATH
        make build

    - name: GIT things
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f book
        git commit -m "add book"
        git remote set-url origin https://${{ secrets.GWION_TOKEN }}@github.com/fennecdjay/Gwion.git
        git push origin :gh-pages || true
        git subtree push --prefix book origin gh-pages
