
name: Coverage Report

on:
  push:
    branches:    
    - '**'
    - '!gh-pages'
  pull_request:
    branches:    
    - '**'
    - '!gh-pages'

jobs:
  build:
    name: Coverage
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - name: Build Gwion
      uses: fennecdjay/gwion-action@v1
      with:
        dir: .
        ref: ${{ github.sha }}
        run: 'true'
      env:
        USE_COVERAGE: 1

    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install gcovr
      run: |
         pip install gcovr
#         pip install git+https://github.com/gcovr/gcovr.git

    - name: Clone report repo
      run: | 
        git clone https://github.com/fennecdjay/gwion-coverage-report
        cd gwion-coverage-report
        git worktree add html origin/gh-pages

    - name: Generate Report
      run: |
        printf '# Gwion coverage\n```\n' > gwion-coverage-report/README.md
        gcovr -s --filter '.*\.c$' src >> gwion-coverage-report/README.md
        printf '```\n' >> gwion-coverage-report/README.md
        COV_TXT=$(gcovr -s --html-details index.html --html-title "Gwion coverage report" --filter '.*\.c$' src | grep lines | cut -d" " -f2)
        COV_NUM=${COV_TXT: : -1}
        echo $COV_NUM > gwion-coverage-report/coverage_num.txt
        sed -i 's/<html>/<script type="text\/javascript" src="..\/focus.js"><\/script><html>/' index.src_*.html
        branch=$(basename ${{ github.event.ref }})
        cd gwion-coverage-report/
        bash old.sh $branch
        bash summary.sh
        cd ..
        gcovr --filter '.*\.c$' src > gwion-coverage-report/html/$branch/lines.txt
        gcovr --filter '.*\.c$' --branches src > gwion-coverage-report/html/$branch/branches.txt
        mv *.html gwion-coverage-report/html/$branch
        cd gwion-coverage-report/
        bash diff.sh $branch
        cat diff.md

    - name: Make badge
      if: github.event_name == 'push' && github.event.ref == 'refs/heads/master'
      run: | 
        cd gwion-coverage-report
        bash badge.sh

    - name: Make html mail
      uses: docker://pandoc/core:2.9
      with:
        args: "--from gfm --to html -o diff.html gwion-coverage-report/diff.md"

    - name: Push Report
      if: github.event_name == 'push'
      run: |
        branch=$(basename ${{ github.event.ref }})
        cp diff.html gwion-coverage-report/html/$branch
        cd gwion-coverage-report
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git remote set-url origin https://${{ secrets.COVERAGE_TOKEN }}@github.com/fennecdjay/gwion-coverage-report.git
        git add README.md coverage_num.txt badge.svg
        git commit -m "Update coverage" || true
        git push || true
        cp focus.js html
        cd html
        git add .
        git commit -m "Update html report"
        git push origin HEAD:gh-pages
#        git push origin --set-upstream origin gh-pages
#        git add -f html
#        git commit -m "Update html report"
#        git subtree push --prefix html origin gh-pages


    - name: Send mail
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: Github Actions job result
        body: file://diff.html
        to: ${{ github.event.repository.owner.email }},${{ github.event.pusher.email }}
        from: Gwion Coverage action
        content_type: text/html
