
name: Coverage Report

on:
  push:
    branches:    
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: submodules
      run: git submodule update --init util ast

    - name: make
      env:
         CFLAGS: -ftest-coverage -fprofile-arcs  
         LDFLAGS: -ftest-coverage -fprofile-arcs
      run: make

    - name: Tests
      env:
        VALGRIND: NO_VALGRIND
        USE_MEMCHECK: 0
        SEVERITY: 3
      run: export GWION_TEST_DIR=${{ runner.tmp }}/tmp/test; mkdir $GWION_TEST_DIR && make test

    - name: Install gcovr
      run: |
         pip install git+https://github.com/gcovr/gcovr.git

    - name: Clone report repo
      run: |
        git clone https://github.com/fennecdjay/gwion-coverage-report
        rm -f gwion-coverage-report/*.html

    - name: Generate Report
      run: |
        COV_TXT=$(gcovr -s --html-details gwion-coverage-report/index.html --filter '.*\.c$' src | grep lines | cut -d" " -f2)
        COV_NUM=${COV_TXT: : -1}
        echo $COV_NUM > gwion-coverage-report/coverage_num.txt
        if [ $(python -c "print( $COV_NUM >= 90 )") = True ]
        then COLOR=green
        elif [ $(python -c "print( $COV_NUM >= 75 )") = True ]
        then COLOR=yellow
        else COLOR=red
        fi
        while true
        do wget https://badgen.net/badge/coverage/$COV_NUM/$COLOR -O gwion-coverage-report/badge.svg && break
        done

    - name: Push Report
      run: |
        cd gwion-coverage-report
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add . 
        git commit -m "Update coverage"
        git remote set-url origin https://${{ secrets.COVERAGE_TOKEN }}@github.com/fennecdjay/gwion-coverage-report.git
        git push origin
