name: Coverage Report

on: [ delete ]

jobs:
  name: Delete obsolete branch
  build:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.ref, 'refs/heads/')"

    steps:
    - name: Clone report repo
      run: |
        git clone https://github.com/fennecdjay/gwion-coverage-report
        cd gwion-coverage-report
        branch=$(basename ${{ github.event.ref }})
        rm -r html/$branch
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git remote set-url origin https://${{ secrets.COVERAGE_TOKEN }}@github.com/fennecdjay/gwion-coverage-report.git
        git add html && git commit -m "Delete obsolete branch" && git subtree push --prefix html origin gh-pages || true
