name: MacOs

on:
  push:
    branches:    
    - '**'
    - '!gh-pages'

jobs:
  build:
    name: ${{ matrix.cc }} ${{ matrix.double && 'double' || 'float'}}
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        cc: [gcc, clang]
        double: [0, 1]

    steps:
    - name: Build Gwion
      uses: fennecdjay/gwion-action@v1
      with:
        ref: ${{ github.sha }}
        run: true
      env:
        CC: ${{ matrix.cc }}
        USE_DEBUG: 1
        USE_DOUBLE: 1
