
name: Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        double: [0, 1]

    steps:
    - uses: actions/checkout@v1
    - name: submodules
      run: git submodule update --init util ast
    - name: make
      env:
         USE_DOUBLE: ${{ matrix.double }}
         CFLAGS: -fsanitize=address -fno-omit-frame-pointer
         LDFLAGS: -fsanitize=address -fno-omit-frame-pointer
      run: make CC=$(which gcc) USE_DOUBLE=${{ matrix.double }}
    - name: make test ${{ runner.temp }}
      env:
        VALGRIND: NO_VALGRIND
        USE_MEMCHECK: 0
        SEVERITY: 3
      run: export GWION_TEST_DIR=${{ runner.tmp }}/tmp/test; mkdir $GWION_TEST_DIR && make test
