name: Windows

on:
  push:
    branches:    
    - '**'
    - '!gh-pages'

jobs:
  build:
    name: Windows ${{ matrix.double && 'double' || 'float '}}
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        double: [0, 1]

    steps:
    - name Checkout
      uses: actions/checkout@v2

    - name: Init submodules
      run: git submodule update --init util ast

    - name: Build
      run: make
      env:
        CC: ${{ matrix.cc }}
        USE_DOUBLE: ${{ matrix.double }}
        USE_DEBUG: 1

    - name: Test
      run: make test
