name: Windows

on:
  push:
    branches:    
    - '**'
    - '!gh-pages'

jobs:
  build:
    name: ${{ matrix.cc }} ${{ matrix.double && 'double' || 'float'}}
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        double: [0, 1]

    steps:
    - name: Build Gwion
      uses: fennecdjay/gwion-action@v6
      with:
        ref: ${{ github.ref }}
        run: true
      env:
        CC: gcc
        USE_DOUBLE: ${{ matrix.double }}
        BUILD_ON_WINDOWS: 1
